### ISSUE TITLE
Could not run mvn verify successfully after launch project and config driver

### ISSUE THREAD

**Issue by liennguyen2811** [liennguyen2811/serenitybasic#1]
1/ Launch successfully serenity project
2/ Config drivers of file config.properties
3/ Run mvn verify

it shows error:
---------------------------------------------------------------------
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - TEST FAILED AT STEP Is the home page
[main] ERROR net.thucydides.core.steps.ConsoleLoggingListener - Could not instantiate class org.openqa.selenium.firefox.FirefoxDriver
[pool-2-thread-1] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: org.fpt.automation.features
[pool-2-thread-3] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: org.fpt.automation.features
[pool-2-thread-2] INFO net.thucydides.core.requirements.PackageRequirementsTagProvider - Loading requirements from package requirements at: org.fpt.automation.features
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 5.2 s <<< FAILURE! - in org.fpt.automation.features.search.SearchByKeywordStory
[ERROR] searching_by_keyword_banana_should_display_the_corresponding_article(org.fpt.automation.features.search.SearchByKeywordStory)  Time elapsed: 1.224 s  <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError:
Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LPP00173386B', ip: '10.88.83.30', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: ProvideNewDriver). See below for more details.
        at org.fpt.automation.features.search.SearchByKeywordStory.searching_by_keyword_banana_should_display_the_corresponding_article(SearchByKeywordStory.java:35)

[ERROR] searching_by_keyword_apple_should_display_the_corresponding_article(org.fpt.automation.features.search.SearchByKeywordStory)  Time elapsed: 0.447 s  <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError:
Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: WIN10
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LPP00173386B', ip: '10.88.83.30', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: driver.version: ProvideNewDriver). See below for more details.
        at org.fpt.automation.features.search.SearchByKeywordStory.searching_by_keyword_apple_should_display_the_corresponding_article(SearchByKeywordStory.java:27)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SearchByKeywordStory.searching_by_keyword_apple_should_display_the_corresponding_article:27 » DriverConfiguration
[ERROR]   SearchByKeywordStory.searching_by_keyword_banana_should_display_the_corresponding_article:35 » DriverConfiguration
[INFO]
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 1
[INFO]
[INFO]
[INFO] --- serenity-maven-plugin:2.0.81:aggregate (serenity-reports) @ webui-selenium ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/LienNTH7/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] current_project.base.dir: D:\SererityProject\webui-selenium
[INFO] Generating test results for 3 tests
[INFO] Loading requirements from tag providers :[net.thucydides.core.requirements.FileSystemRequirementsTagProvider@23bd2f6e, net.thucydides.core.requirements.PackageRequirementsTagProvider@7a78d380]
[INFO] Loading requirements from package requirements at: org.fpt.automation.features
[INFO] LOADED REQUIREMENTS:
REQUIREMENTS:
    - capability : Search {id: Search, displayName: 'Search for definitions', path: features\search, parent: 'null'}
    - feature : Search {id: Search, displayName: 'Search', path: , parent: 'null'}
        - story : Search by keyword story {id: Search by keyword story, displayName: 'Search by keyword story', path: search, parent: 'Search'}

[INFO] 3 requirements loaded after 446 ms
[INFO] 3 related requirements found after 463 ms
[INFO] Generating test outcome reports: false
[INFO] Starting generating reports after 589 ms
[INFO] Configured report threads: 40
[INFO] Test results for 3 tests generated in 2.4 secs
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ webui-selenium ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.293 s
[INFO] Finished at: 2020-02-21T14:13:52+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.1:verify (default) on project webui-selenium: There are test failures.
[ERROR]
[ERROR] Please refer to D:\SererityProject\webui-selenium\target\failsafe-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

D:\SererityProject\webui-selenium>

**Comment by liennguyen2811** [comment]
Da resolved issue. Vi may chua cai firefox
[ERROR] searching_by_keyword_banana_should_display_the_corresponding_article(org.fpt.automation.features.search.SearchByKeywordStory) Time elapsed: 1.224 s <<< ERROR!
net.thucydides.core.webdriver.DriverConfigurationError:
Could not instantiate new WebDriver instance of type class org.openqa.selenium.firefox.FirefoxDriver (Cannot find firefox binary in PATH. Make sure firefox is installed.

**Comment by liennguyen2811** [comment]
Fixed
